[tox]
minversion = 3.25
envlist = py39
skipsdist = true

[testenv]
basepython = python3.9
passenv = *
setenv =
    STORAGE_DRIVER = vfs
deps =
    -rtox-requirements.txt
commands =
    molecule test -s compatibility --destroy always
