FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
      python3 \
      python3-apt \
      sudo \
      curl \
      ca-certificates \
      gnupg \
      lsb-release \
      bash \
      procps \
      iproute2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
